apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: elmi08/fast-note-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: VITE_BACKEND_URL
              value: "http://localhost:8000"  

