name: Deploy Fast Note to MicroK8s

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Backend Docker Image
        run: |
          docker build -t elmi08/fast-note-backend:latest ./backend

      - name: Build Frontend Docker Image
        run: |
          docker build -t elmi08/fast-note-frontend:latest ./frontend

      - name: Login to Docker Hub 
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Backend to Docker Hub
        run: |
          docker push elmi08/fast-note-backend:latest 
      - name: Push Frontend to Docker Hub
        run: |
          docker push elmi08/fast-note-frontend:latest 

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
      
      - name: Deploy Backend to MicroK8s
        run: |
          kubectl apply -f backend/deployment.yaml
          kubectl apply -f backend/service.yaml

      - name: Deploy Frontend to MicroK8s
        run: |
          kubectl apply -f frontend/deployment.yaml
          kubectl apply -f frontend/service.yaml
